In [1]:
import numpy as np

# NumPy

- Permite crear y manipular arrays multidimensionales, que son estructuras similares a listas pero mucho más eficientes para cálculos matemáticos y científicos.
- arrays es similar a lista, es un conjunto de datos
- valores del mismo tipo

## Características, propiedades --> no llevan paréntesis
- .ndim: cantidad de dimensiones de la matriz
- .size: tamaño, cantidad de elementos de la matriz
- .shape: forma de la matriz
- .dtype: muestra el tipo de datos de la matriz
    
## Creación de un array de numpy
  - np.array([]): crea un array a partir de una lista de python
  - np.random.rand: permite crear numeros aleatorio    
  - np.arange(10): nos devuelve un array unidimensional, con numero s consecutivos (1 al 10)
  - np.zeros
  - np.ones
  - np.empty

- Nomenclatura: (filas,columnas)




In [23]:
# Crear un array unidimensional a partir de una lista
lista1= [34, 56, 71, 98, 10]
array1D = np.array(lista1)
print(array1D)

# Crear un array bidimensional a partir de una lista
lista2 = [[23, 34, 56, 68, 54],[67, 78, 90, 54, 13]]
array2D = np.array(lista2)
print("\n")
print ("segundo array")
print(array2D)
# Crear un array de ceros
# Crear un array de unos
# Crear un array de valores aleatorios
# Propiedades del array >

[34 56 71 98 10]


segundo array
[[23 34 56 68 54]
 [67 78 90 54 13]]


In [6]:
print(array1D.ndim)
print(array1D.size)
print(array1D.shape)
print(array1D.dtype)
 

1
5
(5,)
int64


In [9]:
print(array2D.ndim)
print(array2D.size)
print(array2D.shape)
print(array2D.dtype)

2
10
(2, 5)
int64


In [13]:
array_consecutivos = np.arange(20)
print(array_consecutivos)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [14]:
array_zeros = np.zeros((4,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
array_zeros = np.empty((4,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# array con valores aleatorios
array_aleatorio_1 = np.random.randint(7) # array de 1 elem, con 0 incluido y 7 excluido
print(array_aleatorio_1)

4


In [22]:
## sintanxis(numeroempiezo, numerollego, size, tipo)
array_aleatorio_2 = np.random.randint(20, 40, (5,4)) # array de 12 elem, con 20 incluido y 40 excluido
print(array_aleatorio_2)

[[20 36 36 36 26]
 [32 32 25 34 30]
 [20 30 37 39 32]
 [36 34 39 32 34]
 [36 34 26 27 24]]


# Indexación en Arrays

  - array 1d -> array[0] para obtener el primer elemento, igual que en una lista[start:stop:step]
  - array 2d -> array[0,0] para obtener el primer elemento [filas,columnas] [start:stop:step,start:stop:step]
  - array 3d -> array[0,0,0]  para obtener el primer elemento
  

  ## Slicing
  - array[0] accede al primer elemento
  - array[0:2] --> nos devuelve los elementos de la posición 0 y 1
  - array[1:4] obtiene los elementos desde el índice 1 hasta el 3 (el índice final no se incluye)
  - array[0:2,0:2] --> nos devuelve los elementos de la posición 0 y 1 de las filas y columnas  
  - array[0:5:2] obtiene elementos desde el índice 0 hasta el 4, con un paso de 2 (es decir, toma cada segundo elemento).
  - array[-1] accede al último elemento, y array[-3:] obtiene los últimos tres elementos.
  - array[1:4] = [10, 20, 30] reemplaza los elementos en los índices 1, 2 y 3 con los valores 10, 20 y 30.

In [26]:
print (array1D[0])
print (array2D[0][1])
print(array2D[1,1])


34
34
78


In [ ]:
array2D[3,2]

In [31]:
array1D[0:2]

array([34, 56])

In [29]:
# sintaxis(star:stop:step, star:stop:step)
array2D[:, 1:3]

array([[34, 56],
       [78, 90]])

In [32]:
array2D[0:1]

array([[23, 34, 56, 68, 54]])

In [33]:
## todas las filas de la columna 1 hasta el final
array2D[:, 1:]

array([[34, 56, 68, 54],
       [78, 90, 54, 13]])

In [35]:
## todas las filas y las 3 ultimas columnas
array2D[:, -3:]
array2D[:, ::2]

array([[23, 56, 54],
       [67, 90, 13]])

## Filtrado con `np.where()`
- Realiza una evaluación condicional sobre un array. 
- La función `np.where()` devuelve un nuevo array con los elementos seleccionados según la condición especificada.
- Sintaxis: np.where(condición, valor_si_verdadero, valor_si_falso)
 - np.where(array > 5) --> nos devuelve los valores que cumplen la condición
  - np.where(array > 5, "a", "b") --> nos devuelve a si se cumple la condición y b si no se cumple

In [43]:
indices_mayores = np.where(array2D > 30)
print(indices_mayores) ## primera array contiene las filas, segundo array contiene alas columnas



(array([0, 0, 0, 0, 1, 1, 1, 1]), array([1, 2, 3, 4, 0, 1, 2, 3]))


In [40]:
## np.where (condicion, si se cumple, sino cumple)
indices_mayores_2 = np.where(array2D > 30, "adulto", "joven")
indices_mayores_2

array([['joven', 'adulto', 'adulto', 'adulto', 'adulto'],
       ['adulto', 'adulto', 'adulto', 'adulto', 'joven']], dtype='<U6')

In [41]:
indices_mayores_3 = np.where(array2D > 30, array2D, 50)
indices_mayores_3

array([[50, 34, 56, 68, 54],
       [67, 78, 90, 54, 50]])

In [42]:
indices_mayores_4 = np.where(array2D > 30, "adulto", np.where(array2D> 20, "b", "c"))
indices_mayores_4

array([['b', 'adulto', 'adulto', 'adulto', 'adulto'],
       ['adulto', 'adulto', 'adulto', 'adulto', 'c']], dtype='<U6')

In [39]:
## mascaras
mascara = array2D > 30
mascara

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

## Operadores lógicos
- Seleccionar valores basados en dos condiciones
  - Operador `&` para indicar que queremos que se cumplan las dos condiciones => `and`
  - Operador `|` para indicar que se cumpla una condición u otra => `or`

In [45]:
34 in array1D

True

In [48]:
(34 in array1D) | (53 in array1D)

True

In [49]:
mascara = (array2D > 30) & (array2D >60)
print(array2D[mascara])

[68 67 78 90]


# Operaciones Aritméticas con arrays

Operaciones 
  - Se suelen utilizar con arrays con las mismas dimensiones
  - Sumar arrays
  - Restar arrays
  - Multiplicar arrays
  - Dividir arrays
  - Elevar arrays
  - Redondear arrays

In [51]:
array2D2 = np.random.randint(20, 50, size=(2,5))
array2D2 

array([[24, 22, 33, 43, 44],
       [38, 36, 34, 23, 23]])

In [52]:
suma = array2D + array2D2 
suma



array([[ 47,  56,  89, 111,  98],
       [105, 114, 124,  77,  36]])

In [53]:
np.add (array2D2, array2D)

array([[ 47,  56,  89, 111,  98],
       [105, 114, 124,  77,  36]])

In [54]:
## escalar: multiplicar cada elemento por un valor especifico
escalar = 10
print (array2D*escalar)


[[230 340 560 680 540]
 [670 780 900 540 130]]


# Cálculos Estadísticos básicos
- `np.mean(array)` --> calcula la media de los elementos del array
- `np.median(array)` --> calcula la mediana de los elementos del array
- `np.std(array)` --> calcula la desviación estándar de los elementos del array
- `np.var(array)` --> calcula la varianza de los elementos del array
- `np.sum(array)` --> calcula la suma de los elementos del array
- np.min(array) --> calcula el valor mínimo del array
- np.max(array) --> calcula el valor máximo del array

In [55]:
np.sum(array2D)
np.min(array2D)

537

In [57]:
array2D.max(axis=1)

array([68, 90])

In [59]:
array2D.max(axis=0)

array([67, 78, 90, 68, 54])

# Métodos 
- `array.reshape()` --> cambia la forma de la matriz, # El número de elementos tiene que coincidir con la forma del array!!!
- `array.flatten()` --> convierte la matriz en un array de una sola dimensión
- `array.sort()` --> ordena los elementos de la matriz


In [61]:
array1d1 = np.arange(20)
array1d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [62]:
array1d1.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])